package gov.nasa.pds.harvest.mq.msg;

/**
 * A message to harvest collection inventory
 * @author karpenko
 */
public class CollectionInventoryMessage
{
    /**
     * Harvest job ID. Autogenerated UUID.
     */
    public String jobId;
    
    /**
     * Collection lidvid
     */
    public String collectionLidvid;
    
    /**
     * Inventory file path
     */
    public String inventoryFile;
}
