package gov.nasa.pds.harvest.mq.msg;

import java.util.Map;

/**
 * Manager message sent to RabbitMQ
 * @author karpenko
 *
 */
public class ManagerMessage
{
    /**
     * Request ID (Usually autogenerated UUID)
     */
    public String requestId;
    
    /**
     * Command name
     */
    public String command;
    
    /**
     * Command parameters
     */
    public Map<String, String> params;

}
