package gov.nasa.pds.harvest.job;

import java.util.List;
import java.util.Set;

import gov.nasa.pds.registry.common.meta.cfg.FileRefRule;


/**
 * Harvest job configuration parameters (extracted from file message)
 * @author karpenko
 */
public class Job
{
    /**
     * Harvest job ID. Autogenerated UUID.
     */
    public String jobId;
    
    /**
     * PDS node name, such as "PDS_ENG".
     */
    public String nodeName;

    /**
     * List of non-standard date fields, such as "cassini:VIMS_Specific_Attributes/cassini:start_time_doy"
     * to convert to ISO date format.
     * NOTE: Harvest automatically converts fields containing text "date" in the field name.
     */
    public Set<String> dateFields;

    /**
     * List of rules to generate file references.
     */
    public List<FileRefRule> fileRefRules;
}
